directive @upper on FIELD_DEFINITION

type Post {
    id: ID!
    title: String!
    creationDate: Date!
    content: String!
}

type Query {
    post(id: String!): Post!;
    posts(): [Post!]!
}

type Mutation {
    addPost(newPostData: PostInput!): Post!
    updatePost(id: String!, updatedData: PostInput!): Post!
    removePost(id: String!): Boolean!
}

input PostInput {
    title: String!
    content: String!
}
